# Generated by Django 4.1.7 on 2023-03-16 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MajorCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_en', models.CharField(max_length=25)),
                ('name_ko', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='MinorCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_en', models.CharField(max_length=25)),
                ('name_ko', models.CharField(max_length=25)),
                ('major_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.majorcategory')),
            ],
        ),
    ]
