# Generated by Django 4.1.7 on 2023-03-16 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_majorcategory_minorcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwardsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=25, null=True)),
                ('awarded_for', models.CharField(max_length=255, null=True)),
                ('presented_by', models.CharField(max_length=255, null=True)),
                ('first_awarded', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(max_length=700, null=True)),
                ('website', models.URLField(null=True)),
                ('logo', models.ImageField(null=True, upload_to='')),
                ('trophy', models.ImageField(null=True, upload_to='')),
                ('major_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='awards', to='core.majorcategory')),
                ('minor_cateogry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='awards', to='core.minorcategory')),
            ],
        ),
    ]
