# Generated by Django 4.1.7 on 2023-03-16 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_awardsinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='awardsinfo',
            options={'verbose_name_plural': 'AwardsInfo'},
        ),
        migrations.AlterModelOptions(
            name='majorcategory',
            options={'verbose_name_plural': 'MajorCategories'},
        ),
        migrations.AlterModelOptions(
            name='minorcategory',
            options={'verbose_name_plural': 'MinorCategories'},
        ),
        migrations.AlterField(
            model_name='awardsinfo',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='awardsinfo',
            name='trophy',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
