# Generated by Django 4.1.7 on 2023-03-17 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_awardsinfo_options_alter_majorcategory_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ceremony', models.IntegerField()),
                ('date_started', models.DateTimeField(blank=True, null=True)),
                ('date_finished', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=50)),
                ('site', models.CharField(blank=True, max_length=50)),
                ('hosted_by', models.CharField(blank=True, max_length=50)),
                ('produced_by', models.CharField(blank=True, max_length=50)),
                ('directed_by', models.CharField(blank=True, max_length=50)),
                ('logo_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('website', models.URLField(blank=True, null=True)),
                ('awards_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='award', to='core.awardsinfo')),
            ],
        ),
    ]
