# Generated by Django 4.1.7 on 2023-03-17 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_awards'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nominee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('work', models.CharField(blank=True, max_length=50)),
                ('work_awarded', models.BooleanField(default=False)),
                ('is_awarded', models.BooleanField(default=False)),
                ('year_worked', models.IntegerField(blank=True, null=True)),
                ('year_ceremony', models.IntegerField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('awards', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nominee', to='core.awards')),
            ],
        ),
    ]
