# Generated by Django 4.1.7 on 2023-03-17 15:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_nominee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ceremony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('date_started', models.DateTimeField(blank=True, null=True)),
                ('date_finished', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=50)),
                ('site', models.CharField(blank=True, max_length=50)),
                ('hosted_by', models.CharField(blank=True, max_length=50)),
                ('produced_by', models.CharField(blank=True, max_length=50)),
                ('directed_by', models.CharField(blank=True, max_length=50)),
                ('logo_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('website', models.URLField(blank=True, null=True)),
                ('awards_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ceremony', to='core.awardsinfo')),
            ],
            options={
                'verbose_name_plural': 'Ceremonies',
            },
        ),
        migrations.AlterModelOptions(
            name='nominee',
            options={'verbose_name_plural': 'Nominees'},
        ),
        migrations.RemoveField(
            model_name='nominee',
            name='awards',
        ),
        migrations.DeleteModel(
            name='Awards',
        ),
        migrations.AddField(
            model_name='nominee',
            name='ceremony',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='nominee', to='core.ceremony'),
            preserve_default=False,
        ),
    ]
