# Generated by Django 4.1.7 on 2023-03-17 15:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_nominee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='awards',
            old_name='ceremony',
            new_name='index',
        ),
        migrations.RenameModel(
            old_name='Awards',
            new_name='Ceremony',
        ),
        migrations.AlterModelOptions(
            name='nominee',
            options={'verbose_name_plural': 'Nominees'},
        ),
        migrations.RenameField(
            model_name='nominee',
            old_name='awards',
            new_name='ceremony',
        )
    ]
