# Generated by Django 4.1.7 on 2023-03-17 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_awards_ceremony_alter_nominee_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AwardsInfo',
            new_name='Awards',
        ),
        migrations.AlterModelOptions(
            name='awards',
            options={'verbose_name_plural': 'Awards'},
        ),
        migrations.RenameField(
            model_name='awards',
            old_name='minor_cateogry',
            new_name='minor_category',
        ),
        migrations.RenameField(
            model_name='ceremony',
            old_name='awards_info',
            new_name='awards',
        ),
    ]
